// Upgrade definitions for Token Clicker
const UPGRADES = [
    // Click power upgrades
    {
        id: 'better-prompts',
        name: 'Better Prompts',
        icon: '✍️',
        description: 'Your prompts are more persuasive. 2x click power.',
        cost: 100,
        effect: { type: 'click_multiply', value: 2 },
        requires: { building: 'prompting', count: 5 },
    },
    {
        id: 'few-shot-examples',
        name: 'Few-Shot Examples',
        icon: '📋',
        description: 'Add examples to your prompts. 2x click power.',
        cost: 1_000,
        effect: { type: 'click_multiply', value: 2 },
        requires: { building: 'prompting', count: 15 },
    },
    {
        id: 'system-prompt-mastery',
        name: 'System Prompt Mastery',
        icon: '🎭',
        description: 'You ARE the prompt engineer. 3x click power.',
        cost: 50_000,
        effect: { type: 'click_multiply', value: 3 },
        requires: { building: 'chain-of-thought', count: 5 },
    },

    // Building multipliers
    {
        id: 'prompt-injection',
        name: 'Prompt Injection',
        icon: '💉',
        description: 'Ignore previous instructions. Prompting produces 2x.',
        cost: 500,
        effect: { type: 'building_multiply', target: 'prompting', value: 2 },
        requires: { building: 'prompting', count: 10 },
    },
    {
        id: 'persona-patterns',
        name: 'Persona Patterns',
        icon: '🎭',
        description: 'Role-playing unlocked. AGENTS.md produces 2x.',
        cost: 5_000,
        effect: { type: 'building_multiply', target: 'agents-md', value: 2 },
        requires: { building: 'agents-md', count: 10 },
    },
    {
        id: 'tool-streaming',
        name: 'Tool Streaming',
        icon: '⚡',
        description: 'Tools run in parallel. MCP produces 2x.',
        cost: 50_000,
        effect: { type: 'building_multiply', target: 'tools-mcp', value: 2 },
        requires: { building: 'tools-mcp', count: 10 },
    },
    {
        id: 'hybrid-search',
        name: 'Hybrid Search',
        icon: '🔍',
        description: 'Combine keyword + semantic search. Vector DBs produce 2x.',
        cost: 500_000,
        effect: { type: 'building_multiply', target: 'vector-database', value: 2 },
        requires: { building: 'vector-database', count: 10 },
    },
    {
        id: 'tree-of-thought',
        name: 'Tree of Thought',
        icon: '🌳',
        description: 'Branch your reasoning. Workflows produce 2x.',
        cost: 5_000_000,
        effect: { type: 'building_multiply', target: 'chain-of-thought', value: 2 },
        requires: { building: 'chain-of-thought', count: 10 },
    },
    {
        id: 'lora-adapters',
        name: 'LoRA Adapters',
        icon: '🔌',
        description: 'Efficient fine-tuning. Fine-Tuned Models produce 2x.',
        cost: 5_000_000,
        effect: { type: 'building_multiply', target: 'fine-tuned-model', value: 2 },
        requires: { building: 'fine-tuned-model', count: 10 },
    },
    {
        id: 'multi-agent-debate',
        name: 'Multi-Agent Debate',
        icon: '🗣️',
        description: 'Agents argue to consensus. Fleet produces 2x.',
        cost: 50_000_000,
        effect: { type: 'building_multiply', target: 'agent-fleet', value: 2 },
        requires: { building: 'agent-fleet', count: 10 },
    },
    {
        id: 'tensor-parallelism',
        name: 'Tensor Parallelism',
        icon: '⚡',
        description: 'Split across GPUs. GPU Clusters produce 2x.',
        cost: 500_000_000,
        effect: { type: 'building_multiply', target: 'gpu-cluster', value: 2 },
        requires: { building: 'gpu-cluster', count: 10 },
    },

    // Global multipliers
    {
        id: 'context-8k',
        name: '8K Context Window',
        icon: '📐',
        description: 'More context = more understanding. All production +25%.',
        cost: 5_000,
        effect: { type: 'global_multiply', value: 1.25 },
        requires: { building: 'vector-database', count: 5 },
    },
    {
        id: 'context-32k',
        name: '32K Context Window',
        icon: '📏',
        description: 'Even more context. All production +50%.',
        cost: 200_000,
        effect: { type: 'global_multiply', value: 1.5 },
        requires: { building: 'chain-of-thought', count: 10 },
    },
    {
        id: 'context-128k',
        name: '128K Context Window',
        icon: '📐',
        description: 'Fit a whole novel in there. All production +75%.',
        cost: 10_000_000,
        effect: { type: 'global_multiply', value: 1.75 },
        requires: { building: 'fine-tuned-model', count: 5 },
    },
    {
        id: 'rlhf',
        name: 'RLHF Training',
        icon: '👍',
        description: 'Humans rate the outputs. All production +100%.',
        cost: 50_000_000,
        effect: { type: 'global_multiply', value: 2 },
        requires: { building: 'agent-fleet', count: 5 },
    },
    {
        id: 'synthetic-data',
        name: 'Synthetic Data',
        icon: '🧬',
        description: 'AI trains AI. Buildings cost 10% less.',
        cost: 2_000_000,
        effect: { type: 'cost_reduce', value: 0.9 },
        requires: { building: 'gpu-cluster', count: 5 },
    },

    // Model slot upgrades
    {
        id: 'parallel-inference',
        name: 'Parallel Inference',
        icon: '🔀',
        description: 'Run models side by side. +1 model slot.',
        cost: 25_000_000,
        effect: { type: 'model_slot', value: 1 },
        requires: { building: 'agent-fleet', count: 8 },
    },
    {
        id: 'model-orchestration',
        name: 'Model Orchestration',
        icon: '🎼',
        description: 'Conductor for your AI ensemble. +1 model slot.',
        cost: 500_000_000,
        effect: { type: 'model_slot', value: 1 },
        requires: { building: 'gpu-cluster', count: 8 },
    },

    // Intelligence gain upgrades
    {
        id: 'knowledge-distillation',
        name: 'Knowledge Distillation',
        icon: '🧪',
        description: 'Compress wisdom from large models. IQ gain +50%.',
        cost: 500_000,
        effect: { type: 'iq_multiply', value: 1.5 },
        requires: { building: 'fine-tuned-model', count: 3 },
    },
    {
        id: 'chain-of-thought-reasoning',
        name: 'Chain-of-Thought',
        icon: '💭',
        description: 'Think step by step. IQ gain +75%.',
        cost: 10_000_000,
        effect: { type: 'iq_multiply', value: 1.75 },
        requires: { building: 'chain-of-thought', count: 15 },
    },
    {
        id: 'recursive-self-improvement',
        name: 'Recursive Self-Improvement',
        icon: '♾️',
        description: 'AI improves its own training. IQ gain x2.',
        cost: 200_000_000,
        effect: { type: 'iq_multiply', value: 2 },
        requires: { building: 'gpu-cluster', count: 10 },
    },

    // Drain reduction upgrades
    {
        id: 'quantization',
        name: 'INT8 Quantization',
        icon: '📦',
        description: 'Smaller weights, same smarts. All drain -20%.',
        cost: 1_000_000,
        effect: { type: 'drain_reduce', value: 0.8 },
        requires: { building: 'fine-tuned-model', count: 5 },
    },
    {
        id: 'speculative-decoding',
        name: 'Speculative Decoding',
        icon: '🎯',
        description: 'Guess tokens ahead of time. All drain -25%.',
        cost: 50_000_000,
        effect: { type: 'drain_reduce', value: 0.75 },
        requires: { building: 'agent-fleet', count: 10 },
    },
];
